# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\autod\Documents\GitHub\niconvert\niconvert\fz\window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnDownloadXml = QtWidgets.QPushButton(self.groupBox)
        self.btnDownloadXml.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDownloadXml.sizePolicy().hasHeightForWidth())
        self.btnDownloadXml.setSizePolicy(sizePolicy)
        self.btnDownloadXml.setObjectName("btnDownloadXml")
        self.gridLayout.addWidget(self.btnDownloadXml, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.btnBrowseXmlOutput = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseXmlOutput.setObjectName("btnBrowseXmlOutput")
        self.gridLayout.addWidget(self.btnBrowseXmlOutput, 1, 2, 1, 1)
        self.txtXmlOutput = QtWidgets.QLineEdit(self.groupBox)
        self.txtXmlOutput.setClearButtonEnabled(True)
        self.txtXmlOutput.setObjectName("txtXmlOutput")
        self.gridLayout.addWidget(self.txtXmlOutput, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.txtAv = QtWidgets.QLineEdit(self.groupBox)
        self.txtAv.setObjectName("txtAv")
        self.gridLayout.addWidget(self.txtAv, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.btnBrowseAssOutput = QtWidgets.QPushButton(self.groupBox_2)
        self.btnBrowseAssOutput.setAutoFillBackground(False)
        self.btnBrowseAssOutput.setObjectName("btnBrowseAssOutput")
        self.gridLayout_2.addWidget(self.btnBrowseAssOutput, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.btnAssOutput = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAssOutput.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAssOutput.sizePolicy().hasHeightForWidth())
        self.btnAssOutput.setSizePolicy(sizePolicy)
        self.btnAssOutput.setObjectName("btnAssOutput")
        self.gridLayout_2.addWidget(self.btnAssOutput, 2, 2, 1, 1)
        self.btnBrowseXmlInput = QtWidgets.QPushButton(self.groupBox_2)
        self.btnBrowseXmlInput.setObjectName("btnBrowseXmlInput")
        self.gridLayout_2.addWidget(self.btnBrowseXmlInput, 0, 2, 1, 1)
        self.txtXmlInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtXmlInput.setObjectName("txtXmlInput")
        self.gridLayout_2.addWidget(self.txtXmlInput, 0, 1, 1, 1)
        self.txtAssOutput = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtAssOutput.setObjectName("txtAssOutput")
        self.gridLayout_2.addWidget(self.txtAssOutput, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 1, 1, 2)
        self.btnBrowseFilter = QtWidgets.QPushButton(self.groupBox_3)
        self.btnBrowseFilter.setObjectName("btnBrowseFilter")
        self.gridLayout_3.addWidget(self.btnBrowseFilter, 0, 2, 2, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 2, 1)
        self.txtFilter = QtWidgets.QTextEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtFilter.sizePolicy().hasHeightForWidth())
        self.txtFilter.setSizePolicy(sizePolicy)
        self.txtFilter.setObjectName("txtFilter")
        self.gridLayout_3.addWidget(self.txtFilter, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 2, 1, 1)
        self.txtFontSize = QtWidgets.QSpinBox(self.groupBox_4)
        self.txtFontSize.setMaximum(200)
        self.txtFontSize.setProperty("value", 100)
        self.txtFontSize.setObjectName("txtFontSize")
        self.gridLayout_7.addWidget(self.txtFontSize, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox_4)
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout_7.addWidget(self.fontComboBox, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "下载"))
        self.btnDownloadXml.setText(_translate("MainWindow", "下载XML文件"))
        self.label_2.setText(_translate("MainWindow", "输出："))
        self.btnBrowseXmlOutput.setText(_translate("MainWindow", "浏览.."))
        self.txtXmlOutput.setPlaceholderText(_translate("MainWindow", "自动"))
        self.label.setText(_translate("MainWindow", "链接/AV号："))
        self.groupBox_2.setTitle(_translate("MainWindow", "ASS输入/输出"))
        self.label_4.setText(_translate("MainWindow", "输出："))
        self.btnBrowseAssOutput.setText(_translate("MainWindow", "浏览.."))
        self.label_3.setText(_translate("MainWindow", "输入："))
        self.btnAssOutput.setText(_translate("MainWindow", "导出"))
        self.btnBrowseXmlInput.setText(_translate("MainWindow", "浏览.."))
        self.groupBox_3.setTitle(_translate("MainWindow", "弹幕选项"))
        self.label_5.setText(_translate("MainWindow", "屏蔽："))
        self.checkBox.setText(_translate("MainWindow", "顶部弹幕"))
        self.checkBox_2.setText(_translate("MainWindow", "底部弹幕"))
        self.checkBox_3.setText(_translate("MainWindow", "游客弹幕"))
        self.btnBrowseFilter.setText(_translate("MainWindow", "浏览.."))
        self.label_6.setText(_translate("MainWindow", "过滤规则："))
        self.groupBox_4.setTitle(_translate("MainWindow", "字幕选项"))
        self.label_8.setText(_translate("MainWindow", "%"))
        self.label_7.setText(_translate("MainWindow", "字体大小："))
        self.label_9.setText(_translate("MainWindow", "字体："))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.action.setText(_translate("MainWindow", "关于"))


